-- 코드를 작성해주세요


SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY FROM ITEM_INFO AS I INNER JOIN (SELECT L.ITEM_ID FROM ITEM_TREE AS L LEFT JOIN ITEM_TREE AS R ON L.ITEM_ID = R.PARENT_ITEM_ID WHERE R.ITEM_ID IS NULL) AS S ON I.ITEM_ID=S.ITEM_ID ORDER BY I.ITEM_ID DESC