-- 코드를 입력하세요
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES FROM REST_INFO AS R INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) AS F ON F.FOOD_TYPE=R.FOOD_TYPE AND F.FAVORITES = R.FAVORITES ORDER BY R.FOOD_TYPE DESC
