-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY FROM ITEM_INFO AS I INNER JOIN
(SELECT T.ITEM_ID FROM ITEM_TREE AS T INNER JOIN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') AS S ON T.PARENT_ITEM_ID = S.ITEM_ID) AS SS ON I.ITEM_ID = SS.ITEM_ID ORDER BY I.ITEM_ID DESC