-- 코드를 작성해주세요
SELECT F.ID, N.FISH_NAME, F.LENGTH FROM FISH_INFO AS F INNER JOIN (SELECT MAX(LENGTH) AS LENGTH, FISH_TYPE FROM FISH_INFO GROUP BY FISH_TYPE) AS M ON F.FISH_TYPE=M.FISH_TYPE AND F.LENGTH = M.LENGTH INNER JOIN FISH_NAME_INFO AS N ON F.FISH_TYPE=N.FISH_TYPE ORDER BY F.ID

